### ISSUE TITLE
Polynomial division doesn't work

### ISSUE THREAD

**Issue by AxelMatstoms** [ALI-Team/GAMLP#4]
```
>>> (a^2+2*a*b+b^2)/(a+b)   
((1)(((b^2)^2))+(1)(((a^2)^2))+(2)(((b^2)*(a^2)))+(4)(((a^2)*a*b))+(4)(((b^2)*a*b))+(4)(((a*b)^2)))
```
output can be simplifies as a^4+4a^3b+6a^2b^2+4ab^3+b^4 or (a+b)^4
output should be a+b

**Comment by IvarMatstoms** [comment]
Error in PowNode simplifyed expanding of (a+b)^k

**Comment by IvarMatstoms** [comment]
Now simplifies correctly but simplification leaves more to desire.
![dot](https://user-images.githubusercontent.com/17106903/37182893-cecb0ba6-2333-11e8-951d-969781494722.png)

**Comment by IvarMatstoms** [comment]
The issue is resolved
